### ISSUE TITLE
Unable to "make flash" git: 'switch' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by jarleven** [radxa/c100-bootupd#1]
pi@ROS:~/c100-bootupd$ make flash
cd u-boot && \
git switch --detach tegra-l4t-r32.7.3 && \
git am ../patches/*.patch
git: 'switch' is not a git command. See 'git --help'.
Makefile:31: recipe for target 'u-boot/u-boot.bin' failed
make: *** [u-boot/u-boot.bin] Error 1

Complete build log below:

pi@ROS:~$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

pi@ROS:~$ git clone --recurse-submodules https://github.com/LetsOKdo/c100-bootupd.git
Cloning into 'c100-bootupd'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 99 (delta 35), reused 74 (delta 19), pack-reused 0
Unpacking objects: 100% (99/99), done.
Submodule 'u-boot' (git://nv-tegra.nvidia.com/3rdparty/u-boot.git) registered for path 'u-boot'
Cloning into '/home/pi/c100-bootupd/u-boot'...
remote: Enumerating objects: 691095, done.        
remote: Counting objects: 100% (691095/691095), done.        
remote: Compressing objects: 100% (108228/108228), done.        
remote: Total 691095 (delta 573616), reused 691068 (delta 573589), pack-reused 0        
Receiving objects: 100% (691095/691095), 136.85 MiB | 237.00 KiB/s, done.
Resolving deltas: 100% (573616/573616), done.
error: Server does not allow request for unadvertised object 694e3b19f08cbe00a8b6a8f9e959d272a30dfd45
Fetched in submodule path 'u-boot', but it did not contain 694e3b19f08cbe00a8b6a8f9e959d272a30dfd45. Direct fetching of that commit failed.

pi@ROS:~$ cd c100-bootupd/

pi@ROS:~/c100-bootupd$ ./init-jetpack 
[sudo] password for pi: 
Hit:1 http://no.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://no.archive.ubuntu.com/ubuntu bionic-updates InRelease      
Hit:3 http://no.archive.ubuntu.com/ubuntu bionic-backports InRelease    
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [76,9 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [61,0 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2 464 B]
Fetched 229 kB in 2s (136 kB/s)                                                
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxml2-utils is already the newest version (2.9.4+dfsg1-6.1ubuntu1.8).
The following packages were automatically installed and are no longer required:
  gir1.2-goa-1.0 gir1.2-snapd-1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Decompressing Jetson-210_Linux_R32.7.3_aarch64.tbz2...
Decompressing public_sources.tbz2...
~/c100-bootupd/Linux_for_Tegra/source/u-boot ~/c100-bootupd
Decompressing u-boot_src.tbz2...
~/c100-bootupd
~/c100-bootupd/Linux_for_Tegra/source/kernel ~/c100-bootupd
Decompressing kernel_src.tbz2...
~/c100-bootupd
~/c100-bootupd/Linux_for_Tegra/rootfs ~/c100-bootupd
Decompressing Tegra_Linux_Sample-Root-Filesystem_R32.7.3_aarch64.tbz2...
~/c100-bootupd
~/c100-bootupd/Linux_for_Tegra ~/c100-bootupd
Updating rootfs...
Using rootfs directory of: /home/pi/c100-bootupd/Linux_for_Tegra/rootfs
Installing extlinux.conf into /boot/extlinux in target rootfs
/home/pi/c100-bootupd/Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
Root file system directory is /home/pi/c100-bootupd/Linux_for_Tegra/rootfs
Copying public debian packages to rootfs
Start L4T BSP package installation
QEMU binary is not available, looking for QEMU from host system
Found /usr/bin/qemu-aarch64-static
Installing QEMU binary in rootfs
~/c100-bootupd/Linux_for_Tegra/rootfs ~/c100-bootupd/Linux_for_Tegra
Installing BSP Debian packages in /home/pi/c100-bootupd/Linux_for_Tegra/rootfs
Selecting previously unselected package nvidia-l4t-core.
(Reading database ... 142237 files and directories currently installed.)
Preparing to unpack .../nvidia-l4t-core_32.7.3-20221122092935_arm64.deb ...
Pre-installing... skip compatibility checking.
Unpacking nvidia-l4t-core (32.7.3-20221122092935) ...
Setting up nvidia-l4t-core (32.7.3-20221122092935) ...
Selecting previously unselected package jetson-gpio-common.
(Reading database ... 142283 files and directories currently installed.)
Preparing to unpack .../jetson-gpio-common_2.0.17_arm64.deb ...
Unpacking jetson-gpio-common (2.0.17) ...
Selecting previously unselected package python3-jetson-gpio.
Preparing to unpack .../python3-jetson-gpio_2.0.17_arm64.deb ...
Unpacking python3-jetson-gpio (2.0.17) ...
Selecting previously unselected package python-jetson-gpio.
Preparing to unpack .../python-jetson-gpio_2.0.17_arm64.deb ...
Unpacking python-jetson-gpio (2.0.17) ...
Selecting previously unselected package nvidia-l4t-3d-core.
Preparing to unpack .../nvidia-l4t-3d-core_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-3d-core (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-apt-source.
Preparing to unpack .../nvidia-l4t-apt-source_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-apt-source (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-camera.
Preparing to unpack .../nvidia-l4t-camera_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-camera (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-configs.
Preparing to unpack .../nvidia-l4t-configs_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-configs (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-cuda.
Preparing to unpack .../nvidia-l4t-cuda_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-cuda (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-firmware.
Preparing to unpack .../nvidia-l4t-firmware_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-firmware (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-gputools.
Preparing to unpack .../nvidia-l4t-gputools_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-gputools (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-graphics-demos.
Preparing to unpack .../nvidia-l4t-graphics-demos_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-graphics-demos (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-gstreamer.
Preparing to unpack .../nvidia-l4t-gstreamer_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-gstreamer (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-init.
Preparing to unpack .../nvidia-l4t-init_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-init (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-initrd.
Preparing to unpack .../nvidia-l4t-initrd_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-initrd (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-jetson-io.
Preparing to unpack .../nvidia-l4t-jetson-io_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-jetson-io (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-libvulkan.
Preparing to unpack .../nvidia-l4t-libvulkan_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-libvulkan (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-multimedia.
Preparing to unpack .../nvidia-l4t-multimedia_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-multimedia (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-multimedia-utils.
Preparing to unpack .../nvidia-l4t-multimedia-utils_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-multimedia-utils (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-oem-config.
Preparing to unpack .../nvidia-l4t-oem-config_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-oem-config (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-tools.
Preparing to unpack .../nvidia-l4t-tools_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-tools (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-wayland.
Preparing to unpack .../nvidia-l4t-wayland_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-wayland (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-weston.
Preparing to unpack .../nvidia-l4t-weston_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-weston (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-x11.
Preparing to unpack .../nvidia-l4t-x11_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-x11 (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-xusb-firmware.
Preparing to unpack .../nvidia-l4t-xusb-firmware_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-xusb-firmware (32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-kernel.
Preparing to unpack .../nvidia-l4t-kernel_4.9.299-tegra-32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-kernel (4.9.299-tegra-32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-kernel-dtbs.
Preparing to unpack .../nvidia-l4t-kernel-dtbs_4.9.299-tegra-32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-kernel-dtbs (4.9.299-tegra-32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-kernel-headers.
Preparing to unpack .../nvidia-l4t-kernel-headers_4.9.299-tegra-32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-kernel-headers (4.9.299-tegra-32.7.3-20221122092935) ...
Selecting previously unselected package nvidia-l4t-bootloader.
Preparing to unpack .../nvidia-l4t-bootloader_32.7.3-20221122092935_arm64.deb ...
Unpacking nvidia-l4t-bootloader (32.7.3-20221122092935) ...
Setting up jetson-gpio-common (2.0.17) ...
Setting up python3-jetson-gpio (2.0.17) ...
Setting up python-jetson-gpio (2.0.17) ...
Setting up nvidia-l4t-apt-source (32.7.3-20221122092935) ...
Pre-installing... skip changing source list.
Setting up nvidia-l4t-configs (32.7.3-20221122092935) ...
Setting up nvidia-l4t-firmware (32.7.3-20221122092935) ...
Setting up nvidia-l4t-gputools (32.7.3-20221122092935) ...
Setting up nvidia-l4t-init (32.7.3-20221122092935) ...
Setting up nvidia-l4t-libvulkan (32.7.3-20221122092935) ...
Setting up nvidia-l4t-multimedia-utils (32.7.3-20221122092935) ...
Setting up nvidia-l4t-oem-config (32.7.3-20221122092935) ...
Setting up nvidia-l4t-tools (32.7.3-20221122092935) ...
Setting up nvidia-l4t-wayland (32.7.3-20221122092935) ...
Setting up nvidia-l4t-weston (32.7.3-20221122092935) ...
Setting up nvidia-l4t-x11 (32.7.3-20221122092935) ...
Setting up nvidia-l4t-xusb-firmware (32.7.3-20221122092935) ...
Pre-installing xusb firmware package, skip flashing
Setting up nvidia-l4t-kernel (4.9.299-tegra-32.7.3-20221122092935) ...
Using the existing boot entry 'primary'
Pre-installing kernel package, skip flashing
Setting up nvidia-l4t-kernel-dtbs (4.9.299-tegra-32.7.3-20221122092935) ...
Pre-installing kernel-dtbs package, skip flashing
Setting up nvidia-l4t-kernel-headers (4.9.299-tegra-32.7.3-20221122092935) ...
Setting up nvidia-l4t-bootloader (32.7.3-20221122092935) ...
Pre-installing bootloader package, skip flashing
Setting up nvidia-l4t-3d-core (32.7.3-20221122092935) ...
Setting up nvidia-l4t-cuda (32.7.3-20221122092935) ...
Setting up nvidia-l4t-graphics-demos (32.7.3-20221122092935) ...
Setting up nvidia-l4t-initrd (32.7.3-20221122092935) ...
Pre-installing initrd package, skip flashing
Setting up nvidia-l4t-jetson-io (32.7.3-20221122092935) ...
Setting up nvidia-l4t-multimedia (32.7.3-20221122092935) ...
Setting up nvidia-l4t-camera (32.7.3-20221122092935) ...
Setting up nvidia-l4t-gstreamer (32.7.3-20221122092935) ...
Processing triggers for nvidia-l4t-kernel (4.9.299-tegra-32.7.3-20221122092935) ...
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
~/c100-bootupd/Linux_for_Tegra
Removing QEMU binary from rootfs
Removing stashed Debian packages from rootfs
L4T BSP package installation completed!
Rename ubuntu.desktop --> ux-ubuntu.desktop
Disabling NetworkManager-wait-online.service
Disable the ondemand service by changing the runlevels to 'K'
Success!
~/c100-bootupd
JetPack development environment has been set up.

pi@ROS:~/c100-bootupd$ make flash
cd u-boot && \
git switch --detach tegra-l4t-r32.7.3 && \
git am ../patches/*.patch
git: 'switch' is not a git command. See 'git --help'.
Makefile:31: recipe for target 'u-boot/u-boot.bin' failed
make: *** [u-boot/u-boot.bin] Error 1

**Comment by jarleven** [comment]
Git version 2.23.0 introduced a new command [git switch](https://git-scm.com/docs/git-switch/). This command does a subset of what git checkout does (because git checkout does so many different things). You can continue using git checkout for this functionality but the idea is git switch is clearer for those starting out.
"https://salferrarello.com/git-switch/"

Will try :

git --version

sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git

 git --version

**Comment by jarleven** [comment]
### There are multiple issues :
 * git: 'switch' is not a git command. See 'git --help'.
 * Dependencies : bison flex qemu-user-static gcc-aarch64-linux-gnu
 * Makefile {,.bin,.dtb,-dtb.bin}
 * Makefile Looks like you didn’t have any flashed system.img, please remove “-r” in your command   https://forums.developer.nvidia.com/t/how-to-flash-the-changed-dtb-to-jetson-tx2/68359
 
On a clean install of Ubuntu 20.04.5 I was able to "make flash" with the following changes

### Install required packages 
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt update
sudo apt install -y git
sudo apt-get install -y bison flex
sudo apt-get install -y qemu-user-static
sudo apt-get install -y gcc-aarch64-linux-gnu

### Remove the list and copy file by file 
 Linux_for_Tegra/bootloader/t210ref/p3450-0000/u-boot.bin: $(U-BOOT)
       cp u-boot/u-boot.bin Linux_for_Tegra/bootloader/t210ref/p3450-0000
       cp u-boot/u-boot.dtb Linux_for_Tegra/bootloader/t210ref/p3450-0000
       cp u-boot/u-boot-dtb.bin Linux_for_Tegra/bootloader/t210ref/p3450-0000

### Remove the -r flag to build the system.img file
.PHONY: flash
flash: replace-u-boot
	cd Linux_for_Tegra && \
	sudo ./flash.sh jetson-nano-emmc mmcblk0p1

**Comment by jarleven** [comment]
I created "my own" howto here: :
 * https://github.com/jarleven/Salmon/blob/master/NVIDIA_Jetson/BuildImage.md

**Comment by RadxaYuntian** [comment]
The script was developed on a x86 based Arch system. I'll update the repo to fix the compatibility issue with older systems.

**Comment by RadxaYuntian** [comment]
Please check if those issues are fixed in the latest code base.

**Comment by jarleven** [comment]
Thank you for your response ZHANG Yuntian
I managed to get it built (there where multiple issues)

https://github.com/jarleven/Salmon/blob/master/NVIDIA_Jetson/BuildImage.md

The cloning of the submodule normally fails also so I had to checkout the
nvidia stuff manually.
Please note that I'm using this in a classroom so I had to do this multiple
times with the students.

Best regards
Jarl Even Englund

tor. 23. mar. 2023 kl. 03:59 skrev ZHANG Yuntian ***@***.***>:
