### ISSUE TITLE
Create JetPack 6.1 based image

### ISSUE THREAD

**Issue by toperichvania** [radxa/c100-bootupd#3]
Hello,

Is it possible to create new image with JetPack 6.1 as base? 

Thanks!

Kind regards,
Vania

**Comment by RadxaYuntian** [comment]
Jetson Nano is not supported in JetPack 5.0 or above: https://developer.nvidia.com/embedded/jetpack-archive

**Comment by toperichvania** [comment]
Thank you for your quick reply. one more question if you don't mind, is it possible to install this image: https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image

**Comment by RadxaYuntian** [comment]
We only tested against official Nvidia system, so we can't speak about other systems. However, it is likely to work on C100, since it is also based on JetPack 4.6.1.

**Comment by toperichvania** [comment]
OK. Do you perhaps have some instructions on how to make this work on this board? I am trying to understand the README file but I am not on that level yet and would love to be able to understand how to accomplish this.

**Comment by RadxaYuntian** [comment]
It is a 3rd party project so we have no idea how or whether it will work or not. Above was an educated guess.

You should contact that project directly if you have usage issue with their software.

**Comment by toperichvania** [comment]
I was more wondering about ability to boot the system with that image considering the SPI and SDMMC3 difference. Perhaps you can point me in the right direction how to make that work as Readme is not clear to me

**Comment by RadxaYuntian** [comment]
I'm not sure what you mean but we [patched bootloader to enable SDMMC3](https://github.com/LetsOKdo/c100-bootupd/tree/main/patches), which is stored on the eMMC. This is why you can use microSD to boot unmodified Nvidia system on C100.

**Comment by toperichvania** [comment]
Thank you for your quick replies! much appreciated. To be honest, I am not sure my self. I was under impression that in order to boot any system (for example install native Ubuntu or Debian on C100) I would need to do some fixing in order to get these devices booting up with different image rather then one you provided here?

**Comment by RadxaYuntian** [comment]
The stuff we provided here is the source code to create a patched bootloader. You still need to download Nvidia's system image from their website. The whole point of this project is to allow eMMC variant of Jetson Nano to be able to follow the same [Jetson Nano DevKit's tutorial](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit), as normally it won't boot from microSD.

It should be preinstalled in the factory, and as long as you don't wipe the eMMC you can just use microSD to boot other systems.

**Comment by RadxaYuntian** [comment]
If you were talking about the last step it is to create a bootloader recovery image if you wiped it. It is also what we use in the factory to preinstall the bootloader.

**Comment by toperichvania** [comment]
Ah ok. I see. I will then just try to install it and se how it goes. Thank you so much for your help and support!
